DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE "users" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "username" VARCHAR(30) NOT NULL,
  "password" VARCHAR(500) NOT NULL,
  "image_url" VARCHAR(255) NOT NULL
);